---
groups:
  dev:
    hosts:
      - other-dev.example.com

  backend-prod:
    include:
      - backend
    require:
      - prod

  my-system:
    vars:
      EXAMPLE: abc123
    children:
      - frontend
      - backend

hosts:
  frontend.example.com:
    groups:
      - frontend
      - prod
  backend[1:4].example.com:
    groups:
      - backend
      - prod
  dev.example.com:
    vars:
      EXAMPLE: def456
    groups:
      - frontend
      - backend
      - dev
  frontend-stage.example.com:
    groups:
      - frontend
      - stage
  backend-stage.example.com:
    groups:
      - backend
      - stage
